import Footer from "@/components/Footer"
import Header from "@/components/Header"
import "./globals.css"

export const metadata = {
  title: 'Petite Fille',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
