import Footer from "@/components/Footer"
import Header from "@/components/Header"
import "./globals.css"
import { CartProvider } from "@/contexts/CartContexts"

export const metadata = {
  title: 'Petite Fille',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        <main>
          <CartProvider>
            {children}
          </CartProvider>
        </main>
        <Footer />
      </body>
    </html>
  )
}
